/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9ff",
        "surface-dim": "#ccdbf3",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d5e3fc",
        "on-surface": "#0d1c2e",
        "on-surface-variant": "#43474d",
        "inverse-surface": "#233144",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#74777e",
        "outline-variant": "#c4c6ce",
        "surface-tint": "#49607e",
        "primary": "#000f22",
        "on-primary": "#ffffff",
        "primary-container": "#0a2540",
        "on-primary-container": "#768dad",
        "inverse-primary": "#b0c8eb",
        "secondary": "#006c4a",
        "on-secondary": "#ffffff",
        "secondary-container": "#82f5c1",
        "on-secondary-container": "#00714e",
        "tertiary": "#1c0a00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#3b1c00",
        "on-tertiary-container": "#d27200",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d2e4ff",
        "primary-fixed-dim": "#b0c8eb",
        "on-primary-fixed": "#001c37",
        "on-primary-fixed-variant": "#314865",
        "secondary-fixed": "#85f8c4",
        "secondary-fixed-dim": "#68dba9",
        "on-secondary-fixed": "#002114",
        "on-secondary-fixed-variant": "#005137",
        "tertiary-fixed": "#ffdcc3",
        "tertiary-fixed-dim": "#ffb77d",
        "on-tertiary-fixed": "#2f1500",
        "on-tertiary-fixed-variant": "#6e3900",
        "background": "#f8f9ff",
        "on-background": "#0d1c2e",
        "surface-variant": "#d5e3fc"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "md": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "space-2xl": "3rem",
        "space-xs": "0.25rem",
        "gutter": "1rem",
        "space-sm": "0.5rem",
        "gutter-md": "1.5rem",
        "space-md": "1rem",
        "margin-md": "2rem",
        "margin-lg": "3rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "margin": "1rem",
        "gutter-lg": "2rem"
      },
      fontFamily: {
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "bilingual-indicator": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "numeric-data": ["Inter", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
