import { SchemeInfo } from '../types';

export const CENTRAL_STATE_SCHEMES: SchemeInfo[] = [
  {
    id: 'pmegp',
    name: 'PMEGP (Prime Minister Employment Generation)',
    nameHi: 'प्रधानमंत्री रोजगार सृजन कार्यक्रम (PMEGP)',
    ministry: 'Ministry of MSME & KVIC',
    tag: 'Prime Match • 35% Capital Grant',
    matchScore: 96,
    isBestFit: true,
    subsidyRate: '35% (Rural Special)',
    subsidyAmountEst: 297500,
    subsidyDescription: 'Non-refundable capital grant credited directly into bank TDR/escrow. 35% for rural OBC/SC/ST/Women/Minority; 25% for rural General.',
    promoterShare: '5% - 10% (Only ₹42,500 - ₹85,000)',
    loanCeiling: 'Up to ₹50 Lakhs for Manufacturing',
    interestRateRange: '8.4% - 9.1% p.a.',
    keyBenefits: [
      '35% direct non-repayable government capital subsidy',
      'Promoter contribution as low as 5% for special categories',
      'Term loan + working capital combo from Public Sector Banks',
      'Free mandatory 10-day EDP entrepreneurship training via RSETI/portal'
    ],
    eligibilityCriteria: [
      'Age 18+ years, minimum 8th class pass for projects > ₹10L in manufacturing',
      'New business setup (no prior loan defaults)',
      'Rural location certified by Gram Panchayat'
    ],
    requiredDocs: [
      'Aadhaar Card & PAN Card',
      'Detailed Project Report (DPR - generated by UdyamSetu)',
      'Caste / Special Category Certificate (for 35% grant)',
      'Rural Area Certificate from Gram Panchayat / Patwari',
      'Shed Lease Deed / Land ownership proof',
      'Machinery Quotation from registered vendor'
    ],
    applicationUrl: 'https://www.kviconline.gov.in/pmegpeportal/'
  },
  {
    id: 'mudra_kishore',
    name: 'PM Mudra Yojana (Kishore Category)',
    nameHi: 'प्रधानमंत्री मुद्रा योजना (किशोर श्रेणी)',
    ministry: 'Ministry of Finance / SIDBI',
    tag: 'Collateral-Free Bank Credit',
    matchScore: 89,
    isBestFit: false,
    subsidyRate: 'Interest Subvention Eligible',
    subsidyAmountEst: 0,
    subsidyDescription: '100% collateral-free term and working capital credit facility without requiring third-party guarantee.',
    promoterShare: '15% margin money',
    loanCeiling: '₹50,000 to ₹5,00,000 (Kishore) / Up to ₹10,00,000 (Tarun)',
    interestRateRange: '8.5% - 9.5% p.a.',
    keyBenefits: [
      'Zero collateral or third-party guarantee required',
      'Mudra Rupay Card issued for flexible grain and raw material drawing',
      'Zero processing fee for loans up to ₹5 Lakhs',
      'Repayment tenure up to 5 years (60 months) with 6-month moratorium'
    ],
    eligibilityCriteria: [
      'Indian citizen with non-farm income-generating micro business plan',
      'Satisfactory credit score (or new-to-credit rural category)'
    ],
    requiredDocs: [
      'Proof of identity and residential address',
      'Udyam Registration Certificate',
      'Machinery supplier quotation & price estimate',
      '12-Month Projected Balance Sheet & Profit/Loss statement'
    ],
    applicationUrl: 'https://www.udyamimitra.in/'
  },
  {
    id: 'pmfme_odop',
    name: 'PMFME Scheme (ODOP Food Processing)',
    nameHi: 'प्रधानमंत्री सूक्ष्म खाद्य उद्योग उन्नयन योजना (PMFME)',
    ministry: 'Ministry of Food Processing Industries (MoFPI)',
    tag: 'One District One Product (ODOP)',
    matchScore: 92,
    isBestFit: false,
    subsidyRate: '35% Credit-Linked Grant',
    subsidyAmountEst: 297500,
    subsidyDescription: 'Credit-linked capital subsidy at 35% of eligible project cost, with maximum ceiling of ₹10,00,000 per enterprise.',
    promoterShare: '10% minimum contribution',
    loanCeiling: 'Up to ₹30 Lakhs Project Cost',
    interestRateRange: '8.2% - 9.0% p.a.',
    keyBenefits: [
      '35% capital subsidy for food processing machinery & storage',
      '50% grant support for branding, common packaging, and FSSAI labs',
      'Direct convergence with District ODOP cluster benefits',
      'Special seed capital grant of ₹40,000 per SHG member'
    ],
    eligibilityCriteria: [
      'Individual micro food enterprise or FPO / SHG member',
      'Existing or new processing unit aligned with district product'
    ],
    requiredDocs: [
      'FSSAI Registration or intent declaration',
      'Udyam Certificate',
      'Plant layout and electricity sanction copy',
      'Bank statement of promoter for last 6 months'
    ],
    applicationUrl: 'https://pmfme.mofpi.gov.in/'
  },
  {
    id: 'standup_india',
    name: 'Stand-Up India Scheme',
    nameHi: 'स्टैंड-अप इंडिया योजना',
    ministry: 'Department of Financial Services (DFS)',
    tag: 'SC/ST & Women Green-field Focus',
    matchScore: 78,
    isBestFit: false,
    subsidyRate: 'Margin Money Support',
    subsidyAmountEst: 0,
    subsidyDescription: 'Bank loans between ₹10 Lakhs and ₹1 Crore to at least one SC/ST and one Woman borrower per bank branch.',
    promoterShare: '15% margin (can be converged with state subsidies)',
    loanCeiling: '₹10 Lakh to ₹1 Crore',
    interestRateRange: 'MCLR + 3% + Tenor Premium',
    keyBenefits: [
      'Large ticket size funding for comprehensive machinery',
      'Handholding support via SIDBI lead centers',
      'Working capital facility up to ₹10 Lakh by way of overdraft'
    ],
    eligibilityCriteria: [
      'SC/ST and/or Woman entrepreneur',
      'Greenfield enterprise in manufacturing, services, or agri-allied'
    ],
    requiredDocs: [
      'Community / Caste certificate',
      'Comprehensive Project Blueprint and DPR',
      'Pollution / Local Panchayat NOC'
    ],
    applicationUrl: 'https://www.standupmitra.in/'
  }
];
